name: Algo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        cd server
        pip install -r requirements.txt
        python load_weights.py
    - name: Run the app
      run: |
        cd server
        python app.py  &
        sleep 90
        pkill -f "python app.py"
